name: chempred_revision
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - blas=1.0=mkl
  - boost=1.74.0=py39h5472131_5
  - boost-cpp=1.74.0=h75c5d50_8
  - bottleneck=1.3.5=py39h7deecbd_0
  - brotlipy=0.7.0=py39h27cfd23_1003
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2022.12.7=ha878542_0
  - cairo=1.16.0=h19f5f5c_2
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cffi=1.15.0=py39hd667e15_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - colorama=0.4.4=pyhd3eb1b0_0
  - conda=22.11.1=py39hf3d152e_1
  - conda-content-trust=0.1.1=pyhd3eb1b0_0
  - conda-package-handling=1.8.1=py39h7f8727e_0
  - cryptography=36.0.0=py39h9ce1e76_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - cython=0.29.28=py39h295c915_0
  - expat=2.4.9=h6a678d5_0
  - fftw=3.3.9=h27cfd23_1
  - fontconfig=2.14.1=hc2a2eb6_0
  - freetype=2.12.1=hca18f0e_1
  - gensim=4.2.0=py39h6a678d5_0
  - glib=2.69.1=h4ff587b_1
  - greenlet=2.0.1=py39h6a678d5_0
  - icu=70.1=h27087fc_0
  - idna=3.3=pyhd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jbig=2.1=h7f98852_2003
  - jpeg=9e=h166bdaf_2
  - kiwisolver=1.4.2=py39h295c915_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - lerc=3.0=h9c3ff4c_0
  - libdeflate=1.10=h7f98852_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=12.2.0=h65d4601_19
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libpng=1.6.39=h753d276_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.3.0=h542a066_3
  - libuuid=2.32.1=h7f98852_1000
  - libwebp-base=1.2.4=h166bdaf_0
  - libxcb=1.15=h7f8727e_0
  - libzlib=1.2.13=h166bdaf_4
  - llvm-openmp=15.0.6=he0ac6c6_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - matplotlib-base=3.4.3=py39h2fa2bec_2
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39h51133e4_0
  - ncurses=6.3=h7f8727e_2
  - numexpr=2.8.4=py39he184ba9_0
  - numpy=1.23.4=py39h14f4228_0
  - numpy-base=1.23.4=py39h31eccc5_0
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.5.0=h7d73246_0
  - openssl=1.1.1s=h0b41bf4_1
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.5.2=py39h417a72b_0
  - pcre=8.45=h9c3ff4c_0
  - pillow=8.4.0=py39ha612740_0
  - pip=21.2.4=py39h06a4308_0
  - pixman=0.40.0=h36c2ea0_0
  - pluggy=1.0.0=py39h06a4308_1
  - pycairo=1.23.0=py39h23c5bb2_0
  - pycosat=0.6.3=py39h27cfd23_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.9=py39h06a4308_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.12=h12debd9_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytz=2022.1=py39h06a4308_0
  - rdkit=2022.03.2=py39h89e00b9_0
  - readline=8.1.2=h7f8727e_1
  - reportlab=3.5.67=py39hfdd840d_1
  - requests=2.27.1=pyhd3eb1b0_0
  - ruamel.yaml=0.17.21=py39h5eee18b_0
  - ruamel.yaml.clib=0.2.6=py39h5eee18b_1
  - ruamel_yaml=0.15.100=py39h27cfd23_0
  - scipy=1.9.3=py39h14f4228_0
  - selfies=2.1.1=pyhd8ed1ab_0
  - setuptools=61.2.0=py39h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - smart_open=5.2.1=py39h06a4308_0
  - sqlalchemy=1.4.45=py39h72bdee0_0
  - sqlite=3.38.2=hc218d9a_0
  - tk=8.6.11=h1ccaba5_0
  - toolz=0.12.0=py39h06a4308_0
  - tornado=6.2=py39hb9d737c_1
  - tqdm=4.64.1=py39h06a4308_0
  - tzdata=2022a=hda174b7_0
  - urllib3=1.26.8=pyhd3eb1b0_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h166bdaf_4
  - zstd=1.5.2=h8a70e8d_1
  - pip:
      - absl-py==1.3.0
      - cachetools==5.2.0
      - click==8.1.3
      - configargparse==1.5.3
      - fastprogress==1.0.3
      - flask==2.2.2
      - google-auth==2.15.0
      - google-auth-oauthlib==0.4.6
      - grpcio==1.51.1
      - importlib-metadata==5.1.0
      - itsdangerous==2.1.2
      - jinja2==3.1.2
      - markdown==3.4.1
      - markupsafe==2.1.1
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - oauthlib==3.2.2
      - protobuf==3.20.3
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pyonmttok==1.35.0
      - pyyaml==6.0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - sentencepiece==0.1.97
      - smilespe==0.0.3
      - tensorboard==2.11.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - torch==1.13.0
      - torchtext==0.5.0
      - typing-extensions==4.4.0
      - waitress==2.1.2
      - werkzeug==2.2.2
      - zipp==3.11.0
prefix: /home/borneta/miniconda3
